SELECT CUBE_NAME, PROPERTY_NAME, PROPERTY_CAPTION, COLUMN_SQL_TYPE FROM "_SYS_BI"."BIMC_PROPERTIES" 
WHERE  SCHEMA_NAME = '_SYS_BIC' AND "CATALOG_NAME" = 'XXX' AND PROPERTY_TYPE = 1 AND (COLUMN_SQL_TYPE LIKE 'NVAR%' OR COLUMN_SQL_TYPE LIKE 'VAR%') 
AND PROPERTY_CAPTION LIKE '%VEND%' GROUP BY CUBE_NAME, PROPERTY_NAME, PROPERTY_CAPTION, COLUMN_SQL_TYPE ORDER BY PROPERTY_CAPTION
