-- warning: this doesn't show ___T columns which are in the rows with PROPERTY_TYPE = 4.  Same logic doesn't quite work when PROPERTY_TYPE = 4.
SELECT CUBE_NAME, PROPERTY_NAME, PROPERTY_CAPTION, COLUMN_SQL_TYPE FROM "_SYS_BI"."BIMC_PROPERTIES" 
WHERE  SCHEMA_NAME = '_SYS_BIC' AND "CATALOG_NAME" = 'XXX' AND PROPERTY_TYPE = 1 AND (COLUMN_SQL_TYPE LIKE 'NVAR%' OR COLUMN_SQL_TYPE LIKE 'VAR%') 
AND PROPERTY_CAPTION LIKE '%VEND%' GROUP BY CUBE_NAME, PROPERTY_NAME, PROPERTY_CAPTION, COLUMN_SQL_TYPE ORDER BY PROPERTY_CAPTION


-- this searches columns including ___T columns.
SELECT VIEW_NAME ,COLUMN_NAME, DATA_TYPE_NAME , "LENGTH" FROM sys.VIEW_COLUMNS WHERE SCHEMA_NAME = '_SYS_BIC' 
AND (DATA_TYPE_NAME LIKE 'NVAR%' OR DATA_TYPE_NAME LIKE 'VAR%') AND COLUMN_NAME LIKE '%VEND%' 
AND VIEW_NAME LIKE 'XXX%' AND "LENGTH" > 20 ORDER BY COLUMN_NAME
