SELECT PROPERTY_NAME, PROPERTY_CAPTION, COLUMN_SQL_TYPE FROM "_SYS_BI"."BIMC_PROPERTIES" 
WHERE  SCHEMA_NAME = '_SYS_BIC' AND "CUBE_NAME" = 'last part of the view' 
AND "CATALOG_NAME" = 'second last part of the view' AND PROPERTY_TYPE = 1 ORDER BY PROPERTY_NAME
